import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api } from '../api/client'
import Icon from './Icon'
import Modal from './Modal'
import { fmtDate } from '../utils/time'

// Holiday reminders are generated by the server on the fly, so "read" is remembered here.
const HOL_KEY = 'ems_read_holidays'
const readHolidays = () => { try { return JSON.parse(localStorage.getItem(HOL_KEY) || '[]') } catch { return [] } }
const saveHolidays = (ids) => { try { localStorage.setItem(HOL_KEY, JSON.stringify(ids.slice(-60))) } catch { /* ignore */ } }
const isHoliday = (id) => String(id).startsWith('holiday-')

// Re-fetch at most this often. Notifications are read from Google Sheets (60 reads/min quota),
// so there is deliberately NO polling timer: we fetch when the app loads, when the person
// navigates, and when they return to the tab -- and never more than once per interval.
const MIN_REFRESH_MS = 60_000

export function useNotifications(enabled, routeKey) {
  const [notes, setNotes] = useState([])
  const lastFetch = useRef(0)
  const inFlight = useRef(false)

  const refresh = useCallback(async (force = false) => {
    if (!enabled || inFlight.current) return
    if (!force && Date.now() - lastFetch.current < MIN_REFRESH_MS) return
    inFlight.current = true
    lastFetch.current = Date.now()
    try {
      const list = await api.get('/api/employee/notifications')
      if (Array.isArray(list)) {
        const seen = readHolidays()
        setNotes(list.map((n) => (isHoliday(n.id) ? { ...n, isRead: seen.includes(n.id) } : n)))
      }
    } catch { /* not critical: keep showing what we have */ }
    finally { inFlight.current = false }
  }, [enabled])

  useEffect(() => { refresh() }, [refresh, routeKey])

  useEffect(() => {
    if (!enabled) return undefined
    const onVisible = () => { if (document.visibilityState === 'visible') refresh() }
    document.addEventListener('visibilitychange', onVisible)
    return () => document.removeEventListener('visibilitychange', onVisible)
  }, [enabled, refresh])

  const markRead = useCallback(async (id) => {
    setNotes((prev) => prev.map((n) => (n.id === id ? { ...n, isRead: true } : n)))
    if (isHoliday(id)) { saveHolidays([...readHolidays(), id]); return }
    try { await api.patch(`/api/employee/notifications/${id}/read`) } catch { /* will re-sync on next refresh */ }
  }, [])

  const markAllRead = useCallback(async () => {
    setNotes((prev) => {
      saveHolidays([...readHolidays(), ...prev.filter((n) => isHoliday(n.id)).map((n) => n.id)])
      return prev.map((n) => ({ ...n, isRead: true }))
    })
    try { await api.patch('/api/employee/notifications/read-all') } catch { /* will re-sync on next refresh */ }
  }, [])

  const unread = notes.filter((n) => !n.isRead).length
  return { notes, unread, markRead, markAllRead, refresh }
}

export function NotificationBell({ unread, onClick, className = '' }) {
  return (
    <button
      type="button"
      className={`icon-btn bell-btn ${className}`.trim()}
      onClick={onClick}
      aria-label={unread ? `Notifications, ${unread} unread` : 'Notifications'}
    >
      <Icon name="bell" size={20} />
      {unread > 0 && <span className="bell-badge">{unread > 9 ? '9+' : unread}</span>}
    </button>
  )
}

function timeAgo(iso) {
  const t = Date.parse(iso || '')
  if (Number.isNaN(t)) return ''
  const mins = Math.max(0, Math.round((Date.now() - t) / 60000))
  if (mins < 1) return 'just now'
  if (mins < 60) return `${mins} min ago`
  const hrs = Math.round(mins / 60)
  if (hrs < 24) return `${hrs} h ago`
  const days = Math.round(hrs / 24)
  return days < 30 ? `${days} d ago` : fmtDate(iso)
}

const DESTINATIONS = { leave: '/leave', task: '/tasks', holiday: '/dashboard' }

export function NotificationsModal({ notes, unread, markRead, markAllRead, onClose }) {
  const navigate = useNavigate()

  function open(n) {
    if (!n.isRead) markRead(n.id)
    const dest = DESTINATIONS[n.type]
    if (dest) { onClose(); navigate(dest) }
  }

  return (
    <Modal title="Notifications" onClose={onClose}>
      {notes.length === 0 ? (
        <p className="hint-text">You're all caught up. Decisions on your leave requests and tasks will show up here.</p>
      ) : (
        <>
          <div className="toolbar" style={{ marginBottom: 8 }}>
            <span className="hint-text" style={{ margin: 0, flex: 1 }}>{unread ? `${unread} unread` : 'All read'}</span>
            {unread > 0 && <button className="btn btn-secondary btn-sm" onClick={markAllRead}>Mark all as read</button>}
          </div>
          <ul className="notif-list">
            {notes.map((n) => (
              <li key={n.id}>
                <button type="button" className={`notif-item notif-${n.type} ${n.isRead ? '' : 'is-unread'}`} onClick={() => open(n)}>
                  <span className="notif-dot" aria-hidden="true" />
                  <span className="notif-body">
                    <span className="notif-msg">{n.message}</span>
                    <span className="notif-time">{n.type === 'holiday' ? 'Upcoming holiday' : timeAgo(n.createdAt)}</span>
                  </span>
                </button>
              </li>
            ))}
          </ul>
        </>
      )}
    </Modal>
  )
}
